---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: 9x-1x3x10x-1x6x0x0x-1x72x105x0-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 9x-1x3x10x-1x6x0x0x-1x72x105x0
  minReplicas: 1
  maxReplicas: 100000
  metrics:
    - type: Pods
      pods:
        metric:
          name: subleq-metric
        target:
          type: AverageValue
          averageValue: 1
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 100000
        periodSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 100000
        periodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 9x-1x3x10x-1x6x0x0x-1x72x105x0
  labels:
    name: 9x-1x3x10x-1x6x0x0x-1x72x105x0
    namespace: default
spec:
  selector:
    matchLabels:
      name: 9x-1x3x10x-1x6x0x0x-1x72x105x0
  template:
    metadata:
      labels:
        name: 9x-1x3x10x-1x6x0x0x-1x72x105x0
        plane: control
    spec:
      containers:
        - name: app
          image: gcr.io/pixie-oss/pixie-dev/demo/http_echo_image:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-9x-1x3x10x-1x6x0x0x-1x72x105x0
  labels:
    name: 9x-1x3x10x-1x6x0x0x-1x72x105x0
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: 9x-1x3x10x-1x6x0x0x-1x72x105x0
